### PR TITLE
moving webpack to suplementary content

### PR DESCRIPTION
**Pull request by askingalot**
As per our discussion in friday's meeting....

### CODE REVIEW

**Comment by JoeShep** [comment]
"removed request for JoeShep and jisie 5 minutes ago". Fine. I can take a hint

**Comment by askingalot** [comment]
> "removed request for JoeShep and jisie 5 minutes ago". Fine. I can take a hint

I originally added three people to review it and then I realized that I was asking three people to look at a link I moved a short distance down the page...and that seemed extreme.

**Comment by jisie** [comment]
😢

**Comment by askingalot** [comment]
**Note to self:** _stick to C#_

**Pull request merged**
