### PR TITLE
Kb cs concepts

### PR DESCRIPTION
**Pull request by kimberly-bird**
@stevebrownlee Here is a markdown of the google doc I made for cohort 28 (https://docs.google.com/document/d/1bII8_20FpCkGufEGT8IY8jWWWfAiRAt8nDcvlyTtY-E/edit?usp=sharing)

Thinking it could be a good addition to the "graduate" chapter - I tried to make it a Python/C# combo so that students from any cohort could refer to it. Also, several students in 28 have asked for the C# references with Python for the google doc because many are applying for C# jobs.

Let me know what you think! It's like 50 miles long, so ... it's a lot. ;)

### CODE REVIEW

**Comment by stevebrownlee** [comment]
This is a lot. I made some modifications in your document by striking out some incorrect phrasing and placing corrections after it.

Also, not seeing any Markdown for your doc. Let's review this in person so we can work through it.

**Comment by askingalot** [comment]
Wow, @kimberly-bird, this is a lot of good stuff.

I think this could turn into at least three documents. One for python-specific topics, one for C#-specific, and one for general topics. Most of your document would fall into the general category.

I'd also like to see C# code examples added alongside the python examples (for the general topics).

**Comment by kimberly-bird** [comment]
@stevebrownlee It is a TON, right!? Bah. I'd love to review this with you to see how we can make it better (and fix the Markdown). I would like to see this used during the interviewing period by cohort 28 to provide a quick reference/study guide on these topics to help as they interview prep.

I agree with @askingalot - moving them into 3 or even 4 separate docs could make it more digestible. @askingalot, I started this as a Python doc for 28, so I'm slowly getting more C# examples in there. ;)

**Comment by stevebrownlee** [comment]
Closing this ticket as it was decided to create a separate repository to hold this information

https://github.com/nashville-software-school/the-graduate

**Pull request closed without merging**
